export const islandCountries = [
  "Australia",
  "Madagascar",
  "New Zealand",
  "Papua New Guinea",
  "Japan",
  "Indonesia",
  "Philippines",
  "United Kingdom",
  "Iceland",
  "Cuba",
  "Jamaica",
  "Haiti",
  "Dominican Republic",
  "Cyprus",
  "Sri Lanka",
  "Maldives",
  "Taiwan",
  "Fiji",
  "Bahamas",
  "Malta",
  "Maldives",
  "Seychelles",
  "Marshall Islands",
  "Solomon Islands",
  "Kiribati",
  "Nauru",
  "Tuvalu",
  "Vanuatu",
  "Palau",
  "Comoros",
  "São Tomé and Príncipe",
  "Cape Verde",
  "Bahrain",
  "Singapore",
  "Mauritius",
  "Bahrain",
  "Tonga",
  "Saint Kitts and Nevis",
  "Antigua and Barbuda",
  "Barbados",
  "Grenada",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Dominica",
  "Trinidad and Tobago",
  "Falkland Islands",
];
