export const islandCountries = [
  "Antigua and Barbuda",
  "Australia",
  "Bahamas",
  "Bahrain",
  "Barbados",
  "Cape Verde",
  "Comoros",
  "Cuba",
  "Cyprus",
  "Dominica",
  "Dominican Republic",
  "Falkland Islands",
  "Fiji",
  "Greenland",
  "Grenada",
  "Haiti",
  "Iceland",
  "Indonesia",
  "Ireland",
  "Jamaica",
  "Japan",
  "Kiribati",
  "Madagascar",
  "Maldives",
  "Malta",
  "Marshall Islands",
  "Mauritius",
  "Nauru",
  "New Caledonia",
  "New Zealand",
  "Northern Cyprus",
  "Palau",
  "Papua New Guinea",
  "Philippines",
  "Puerto Rico",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "São Tomé and Príncipe",
  "Seychelles",
  "Singapore",
  "Solomon Islands",
  "Sri Lanka",
  "Taiwan",
  "Tonga",
  "Trinidad and Tobago",
  "Tuvalu",
  "United Kingdom",
  "Vanuatu",
];
